<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Materialises the catalog responses into the immutable fixtures file.
 *
 * Usage: php cli/edgecase_emit_fixtures.php
 *
 * @package    local_catquiz
 * @copyright  2026 Wunderbyte GmbH <info@wunderbyte.at>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

define('CLI_SCRIPT', true);
require(__DIR__ . '/../../../config.php');
require_once(__DIR__ . '/edgecase_lib.php');

use local_catquiz\local\model\model_model;

/**
 * Exports a value using short array syntax with no trailing whitespace.
 *
 * @param mixed $value
 * @param int $indent
 * @return string
 */
function edgecase_export_short($value, int $indent = 8): string {
    if (is_array($value)) {
        $pad = str_repeat(' ', $indent);
        $inner = str_repeat(' ', $indent + 4);
        $islist = array_keys($value) === range(0, count($value) - 1);
        $lines = [];
        foreach ($value as $k => $v) {
            $prefix = $islist ? '' : var_export((string) $k, true) . ' => ';
            $lines[] = $inner . $prefix . edgecase_export_short($v, $indent + 4);
        }
        return "[\n" . implode(",\n", $lines) . ",\n" . $pad . ']';
    }
    if (is_null($value)) {
        return 'null';
    }
    if (is_bool($value)) {
        return $value ? 'true' : 'false';
    }
    if (is_string($value)) {
        return var_export($value, true);
    }
    return (string) $value;
}

$header = <<<'HDR'
<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Immutable edge-case fixtures for IP estimation on pathological geometries.
 *
 * Each fixture persists seed, generator parameters, the materialised responses
 * (as [ability, response] pairs) and the expected identifiability class, so the
 * regression data survives changes to the RNG, generator or model. Generated by
 * cli/edgecase_emit_fixtures.php. Do not edit by hand.
 *
 * Expectation classes: F (unique finite optimum), B (boundary optimum),
 * W (weakly identified / flat likelihood), N (no unique finite maximum).
 *
 * @package    local_catquiz
 * @copyright  2026 Wunderbyte GmbH <info@wunderbyte.at>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

return [

HDR;

$out = $header;
foreach (edgecase_catalog() as $case) {
    $model = model_model::get_instance($case['model']);
    $responses = edgecase_build_responses($model, $case);
    $pairs = [];
    foreach ($responses as $r) {
        $pairs[] = '[' . round($r->get_personparams()->get_ability(), 6) . ', '
            . rtrim(rtrim(sprintf('%.4f', $r->get_response()), '0'), '.') . ']';
    }
    $gen = edgecase_export_short($case['generator'], 8);
    $out .= "    '{$case['id']}' => [\n";
    $out .= "        'id' => '{$case['id']}',\n";
    $out .= "        'model' => '{$case['model']}',\n";
    $out .= "        'estimation' => '{$case['estimation']}',\n";
    $out .= "        'class' => '{$case['class']}',\n";
    $out .= "        'seed' => {$case['seed']},\n";
    $out .= "        'expected' => '{$case['expected']}',\n";
    $out .= "        'generator' => {$gen},\n";
    $out .= "        'responses' => [\n";
    foreach ($pairs as $pair) {
        $out .= "            {$pair},\n";
    }
    $out .= "        ],\n";
    $out .= "    ],\n";
}
$out .= "];\n";

file_put_contents(__DIR__ . '/../tests/fixtures/edgecase_ip_fixtures.php', $out);
echo 'Fixtures written (' . number_format(strlen($out)) . " bytes, "
    . count(edgecase_catalog()) . " fixtures)\n";
