name: Labeled ERPNext Task

on:
  issues:
    types:
      - labeled

jobs:
  create-task:
    runs-on: ubuntu-latest

    steps:
      - name: Format Payload
        run: |
          echo '{
            "subject": "GH#${{ github.event.issue.number }} - ${{ github.event.issue.title }}",
            "project": "${{ github.event.label.name }}",
            "status": "Open",
            "description": "<p><a href=\"${{ github.event.issue.html_url }}\">GH#${{ github.event.issue.number }}</a></p><br>${{ github.event.issue.body }}"
            }' > payload.json

      - name: Make API Request to ERPNext
        run: |
          response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.WEBHOOK_TOKEN }}" \
            -d @payload.json \
            -w "\n%{http_code}" \
            https://erp.wunderbyte.at/api/resource/Task)

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "Response body: $body"
          echo "Status code: $http_code"

          if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
            echo "API call failed with status code $http_code"
            exit 1
          fi
