name: Moodle Plugin CI Push

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      mariadb:
        image: mariadb:10.8
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.3
            moodle-branch: MOODLE_405_STABLE
            database: pgsql
          - php: 8.3
            moodle-branch: MOODLE_405_STABLE
            database: mariadb
          - php: 7.4
            moodle-branch: MOODLE_401_STABLE
            database: pgsql
            extensions: mbstring, curl, zip, gd, xmlrpc, soap, intl, exif
          - php: 7.4
            moodle-branch: MOODLE_401_STABLE
            database: mariadb
            extensions: mbstring, curl, zip, gd, xmlrpc, soap, intl, exif, mysqli

    steps:
      - name: Clean workspace for matrix job
        run: |
          MATRIX_ID="${{ matrix.php }}-${{ matrix.database }}-${{ matrix.moodle-branch }}"
          rm -rf "$GITHUB_WORKSPACE"
          mkdir -p "$GITHUB_WORKSPACE/matrix-$MATRIX_ID"
          echo "MATRIX_DIR=matrix-$MATRIX_ID" >> $GITHUB_ENV

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: ${{ env.MATRIX_DIR }}/plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8

      - name: Install moodle-plugin-ci
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        run: |
          moodle-plugin-ci add-plugin --branch main Wunderbyte-GmbH/moodle-local_wunderbyte_table
          moodle-plugin-ci add-plugin --branch catmodel_main Wunderbyte-GmbH/moodle-mod_adaptivequiz
          moodle-plugin-ci add-plugin --branch master branchup/moodle-filter_shortcodes
          moodle-plugin-ci add-plugin --branch main Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz

          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
          MUSTACHE_IGNORE_NAMES: 'feedbackform_collapsible_close.mustache,feedbackform_collapsible_open.mustache,catscaleshortcodetablechildren.mustache'

      - name: PHP Lint
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: PHP Copy/Paste Detector
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker --max-warnings 0

      - name: Moodle PHPDoc Checker
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc

      - name: Validating
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: PHPUnit tests
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit --testdox

      - name: Behat features
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: |
          # Clean up any existing selenium container
          docker rm -f selenium || true
          # Run the Behat tests with a specific Selenium image
          moodle-plugin-ci behat --profile chrome --selenium selenium/standalone-chrome:latest


      - name: Clean up Docker containers
        if: ${{ always() }}
        run: |
          CONTAINER_NAME="selenium-${{ matrix.php }}-${{ matrix.database }}-${{ github.run_id }}"
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
